name: gccabo
description: "A new Flutter project."



version: 1.0.0+1

environment:
  sdk: ^3.10.3


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  cloud_firestore: ^4.17.3
  intl: ^0.18.1
  pdf: ^3.11.0
  path_provider: ^2.1.5
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/Tema 1 ESTATUTO DEL PERSONAL DE LA GUARDIA CIVIL/
    - assets/Tema 2 RÉGIMEN INTERIOR/
    - assets/Tema 3 DEONTOLOGÍA PROFESIONAL/
    - assets/Tema 4 DERECHOS HUMANOS/
    - assets/Tema 5 DERECHO ADMINISTRATIVO/
    - assets/Tema 6 PROTECCIÓN DE LA SEGURIDAD CIUDADANA/
    - assets/Tema 7 DERECHO FISCAL/
    - assets/Tema 8 ARMAS, EXPLOSIVOS, ARTÍCULOS PIROTÉCNICOS Y CARTUCHERÍA/
    - assets/Tema 9 PATRIMONIO NATURAL Y BIODIVERSIDAD/
    - assets/Tema 10 PROTECCIÓN INTEGRAL CONTRA LA VIOLENCIA DE GÉNERO Y ACTUACIÓN CON MENORES/
    - assets/Tema 11 DERECHO PENAL/
    - assets/Tema 12 PODER JUDICIAL/
    - assets/Tema 13 LEY DE ENJUICIAMIENTO CRIMINAL/
    - assets/Tema 14 IGUALDAD EFECTIVA DE MUJERES Y HOMBRES/
    - assets/Tema 15 PROTECCION CIVIL/
    - assets/Tema 16 TECNOLOGIAS DE LA INFORMACION Y LA COMUNICACION/
    - assets/TEMA 17 TOPOGRAFIA/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
